Catkin-ProjectName: langs
Version: 0.2.0
Description: meta package for language bindings.

Depends: catkin, genmsg, gencpp, genpy
Author: The ROS Ecosystem
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-DebRulesType: cmake
Catkin-CopyrightType:  willowgarage

